name: Web

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build amd64
      run: docker build . --tag opennetwork/web:linux-amd64
    
    - name: Push amd64
      run: docker push opennetwork/web:linux-amd64
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEMO_HOST }}
        username: ${{ secrets.DEMO_USERNAME }}
        key: ${{ secrets.DEMO_KEY }}
        port: ${{ secrets.DEMO_PORT }}
        script: |
            whoami