name: Web

on:
  push:
    branches:
    - main
    paths:
    - './**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build amd64
      run: docker build . --tag opennetwork/web:linux-amd64
    
    - name: Push amd64
      run: docker push opennetwork/web:linux-amd64
    